package dev.wntrmute.ans

import android.content.Context
import android.media.AudioAttributes
import android.media.MediaPlayer
import android.os.Handler
import android.os.Looper
import android.util.Log

/**
 * Plays a number-station broadcast from pre-recorded audio clips bundled in
 * `res/raw`, with sine-wave tones generated by [TonePlayer] mixed in for VOX
 * keying. Replaces the previous `android.speech.tts.TextToSpeech`-backed
 * implementation so the app works on devices with no installed TTS engine
 * (notably GrapheneOS without Google services).
 *
 * Every pass opens with an 800 Hz tone to key a VOX-enabled radio. The first
 * pass also plays a time-of-day greeting clip ("Good morning" / etc.) after
 * that tone; subsequent repeats omit the greeting and go straight to digits.
 * Digits are spoken from individual clips with a short pause between digits
 * and a longer pause between five-digit groups. Between repeats, a 432 Hz
 * tone marks the end of the repeat. After the final pass in a finite
 * broadcast, a 432 Hz tone plays just before the "Good bye for now" clip as
 * a signoff. Loop-until-stopped mode has no signoff.
 *
 * The internal sequencer turns the per-pass plan into a flat list of [Step]s
 * (tone, silence, clip) and runs them one at a time on the main thread — tones
 * advance after their fixed duration; clips advance on `OnCompletionListener`.
 * A session id guards against callbacks from a flushed queue after [stop].
 */
class NumberStationPlayer(private val context: Context) {

    /** Invoked on the main thread whenever playback starts or stops. */
    var onPlayingChanged: ((Boolean) -> Unit)? = null

    /** Invoked on the main thread when audio cannot be played. */
    var onError: ((String) -> Unit)? = null

    /**
     * Which bundled voice set to use. Default is [Voice.Fiona]; [Voice.Tessa]
     * is shipped but no UI surfaces it yet — wire a settings toggle to flip
     * this property when needed.
     */
    var voice: Voice = Voice.Fiona

    private val main = Handler(Looper.getMainLooper())
    private val tonePlayer = TonePlayer()

    private var playing = false
    private var sessionId = 0

    private var groups: List<String> = emptyList()
    private var plan = RepeatPlan(repeat = false, loopForever = false, plays = 1)
    private var firstPass = true

    private val queue: ArrayDeque<Step> = ArrayDeque()
    private var currentClip: MediaPlayer? = null
    private var audioAttributes: AudioAttributes? = null

    val isPlaying: Boolean get() = playing

    /** Route tones and audio clips through the given attributes (media stream). */
    fun setAudioAttributes(attributes: AudioAttributes) {
        audioAttributes = attributes
        tonePlayer.audioAttributes = attributes
    }

    /**
     * Begin playback of [groups]. When [repeat] is false the message is read
     * once; otherwise it loops forever if [loopForever], or is read [plays]
     * times.
     */
    fun start(groups: List<String>, repeat: Boolean, loopForever: Boolean, plays: Int) {
        if (groups.isEmpty()) return
        if (playing) stop()
        this.groups = groups
        plan = RepeatPlan(repeat, loopForever, plays)
        firstPass = true
        sessionId++
        setPlaying(true)
        enqueuePass()
        runNext(sessionId)
    }

    fun stop() {
        if (!playing && queue.isEmpty()) return
        sessionId++ // invalidate in-flight callbacks
        queue.clear()
        tonePlayer.stop()
        releaseCurrentClip()
        main.removeCallbacksAndMessages(null)
        setPlaying(false)
    }

    /** Release all resources. Safe to call from a service's `onDestroy`. */
    fun shutdown() {
        stop()
    }

    private fun onPassComplete() {
        if (!playing) return
        if (plan.completePass()) {
            enqueuePass()
            runNext(sessionId)
        } else {
            setPlaying(false)
        }
    }

    private fun enqueuePass() {
        val isLast = !plan.isInfinite && plan.remaining == 1
        val isFirst = firstPass
        firstPass = false

        // Lead-in: 800 Hz tone (keys VOX), brief gap inside VOX hang, then
        // the greeting clip on the very first pass only.
        queue += Step.PlayTone(LEAD_HZ, LEAD_TONE_MS)
        queue += Step.Silence(LEAD_TONE_GAP_MS)
        if (isFirst) {
            queue += Step.PlayClip(greetingResId())
            queue += Step.Silence(LEAD_SILENCE_MS)
        }

        // Digits: each digit clip followed by an inter-digit silence; the
        // last digit in each group (including the final group) uses the
        // longer group-pause silence so the cadence before the end-of-sequence
        // tone matches the cadence between groups.
        for (group in groups) {
            for ((di, digit) in group.withIndex()) {
                val lastDigit = di == group.lastIndex
                queue += Step.PlayClip(digitResId(digit))
                queue += Step.Silence(if (lastDigit) GROUP_PAUSE_MS else INTER_DIGIT_MS)
            }
        }

        if (isLast) {
            // Final pass: longer 432 Hz tone, gap, signoff clip, tail silence.
            queue += Step.PlayTone(END_HZ, BYE_LEAD_TONE_MS)
            queue += Step.Silence(BYE_LEAD_GAP_MS)
            queue += Step.PlayClip(lookupResId(GOODBYE_NAME))
            queue += Step.Silence(BYE_TAIL_MS)
        } else {
            // Non-final pass: shorter 432 Hz tone + inter-pass pause.
            queue += Step.PlayTone(END_HZ, END_TONE_MS)
            queue += Step.Silence(INTER_PASS_PAUSE_MS)
        }
        queue += Step.PassEnd
    }

    private fun runNext(session: Int) {
        if (session != sessionId || !playing) return
        val step = queue.removeFirstOrNull() ?: run {
            // Queue ran dry without a PassEnd marker — treat as a pass end so
            // the repeat plan can stop or kick off the next pass.
            onPassComplete()
            return
        }
        when (step) {
            is Step.PlayTone -> {
                tonePlayer.play(step.hz, step.ms)
                main.postDelayed({ runNext(session) }, step.ms.toLong())
            }
            is Step.Silence -> {
                if (step.ms <= 0L) {
                    runNext(session)
                } else {
                    main.postDelayed({ runNext(session) }, step.ms)
                }
            }
            is Step.PlayClip -> playClip(step.rawResId, session)
            is Step.PassEnd -> onPassComplete()
        }
    }

    private fun playClip(rawResId: Int, session: Int) {
        if (rawResId == 0) {
            main.post { onError?.invoke("Missing audio resource for the ${voice.label} voice.") }
            setPlaying(false)
            return
        }
        val mp = MediaPlayer()
        try {
            audioAttributes?.let { mp.setAudioAttributes(it) }
            context.resources.openRawResourceFd(rawResId).use { afd ->
                mp.setDataSource(afd.fileDescriptor, afd.startOffset, afd.length)
            }
            mp.prepare() // clips are tiny; synchronous prep is fast
        } catch (e: Exception) {
            Log.w(TAG, "Failed to prepare clip resId=$rawResId", e)
            safeRelease(mp)
            main.post { onError?.invoke("Failed to play audio clip.") }
            setPlaying(false)
            return
        }
        currentClip = mp
        mp.setOnCompletionListener {
            if (currentClip === it) currentClip = null
            safeRelease(it)
            runNext(session)
        }
        mp.setOnErrorListener { player, what, extra ->
            Log.w(TAG, "MediaPlayer error what=$what extra=$extra")
            if (currentClip === player) currentClip = null
            safeRelease(player)
            main.post { onError?.invoke("Audio playback error.") }
            setPlaying(false)
            true
        }
        mp.start()
    }

    private fun releaseCurrentClip() {
        currentClip?.let { safeRelease(it) }
        currentClip = null
    }

    private fun safeRelease(mp: MediaPlayer) {
        try {
            if (mp.isPlaying) mp.stop()
        } catch (_: IllegalStateException) {
        }
        try {
            mp.release()
        } catch (_: IllegalStateException) {
        }
    }

    private fun setPlaying(value: Boolean) {
        if (playing == value) return
        playing = value
        main.post { onPlayingChanged?.invoke(value) }
    }

    // --- Resource resolution ---

    private fun greetingResId(): Int = lookupResId(currentGreeting().rawName)

    private fun digitResId(digit: Char): Int = lookupResId("digit_$digit")

    private fun lookupResId(phraseName: String): Int =
        context.resources.getIdentifier(voice.prefix + phraseName, "raw", context.packageName)

    // --- Step types ---

    private sealed class Step {
        data class PlayTone(val hz: Int, val ms: Int) : Step()
        data class Silence(val ms: Long) : Step()
        data class PlayClip(val rawResId: Int) : Step()
        object PassEnd : Step()
    }

    /** Bundled voice set selectable by future settings UI. */
    enum class Voice(val prefix: String, val label: String) {
        Fiona(prefix = "", label = "Fiona"),
        Tessa(prefix = "tessa_", label = "Tessa"),
    }

    private companion object {
        const val TAG = "NumberStationPlayer"

        const val LEAD_HZ = 800
        const val LEAD_TONE_MS = 700
        const val LEAD_TONE_GAP_MS = 200L
        const val LEAD_SILENCE_MS = 400L

        const val INTER_DIGIT_MS = 200L
        const val GROUP_PAUSE_MS = 700L

        const val END_HZ = 432
        const val END_TONE_MS = 500
        const val INTER_PASS_PAUSE_MS = 500L

        const val BYE_LEAD_TONE_MS = 700
        const val BYE_LEAD_GAP_MS = 200L
        const val BYE_TAIL_MS = 500L

        const val GOODBYE_NAME = "good_bye"
    }
}
